blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ General Question / Support
    url: https://github.com/Martin13025/crawrix/discussions
    about: Please ask general questions or request help in GitHub Discussions.
issue_templates:
  - name: ğŸ Bug Report
    description: Report a bug to help improve the project
    labels: [bug]
    file: bug_report.md
  - name: âœ¨ Feature Request
    description: Suggest a new idea or enhancement
    labels: [enhancement]
    file: feature_request.md
